### ISSUE TITLE
Add startup hook

### ISSUE THREAD

**Issue by sfrique** [spfguru/dehydrated4googlecloud#2]
This hooks is failing because of new startup hook

https://github.com/lukas2511/dehydrated/commit/60583d3ef9a62712851adeb488c7b454dc36ccbf

https://github.com/lukas2511/dehydrated/issues/411

**Comment by sfrique** [comment]
You may also need exit_hook.

Sorry, I don't have time to make an PR right now.

**Comment by LordBrain** [comment]
I am hitting this right now. What is the work around for it?

**Comment by fogs** [comment]
Should be fixed with the latest commit. Can anyone confirm?

**Comment by fogs** [comment]
Works for me, closing this issue due to lack of any other response.
